[package]
name = "S1"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
serde_yaml = "0.9.33"
tokio = { version = "1.42.0", features = ["full"] }
reqwest = { version = "0.12.12", features = ["json", "blocking"] }
